image: node:lts
before_script:
  - npm ci
pages:
  script:
    - npm install
    - npm run build
    - rf -rf public
    - cp -r docs/guide public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH